/**
 * LocalGeocoder — offline geocoding using static OSM data.
 * Loads mvd-geocoder-data.json (generated by scripts/fetch-mvd-osm-data.ts).
 * Falls back gracefully if the data file doesn't exist.
 */
import { readFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { normalizeText } from "./search.js";
import type { GeoPoint, GeoPlace } from "./geocode.js";

interface OsmPoi {
  n: string; // name (original)
  t: string; // type
  la: number; // lat
  lo: number; // lon
}

interface OsmStreet {
  n: string; // normalized name
  nodes: [number, number][]; // [lat, lon] pairs
}

interface GeocoderData {
  generatedAt: string;
  pois: OsmPoi[];
  streets: OsmStreet[];
}

/** Approximate distance in meters between two lat/lon points (Montevideo area). */
function approxDistanceMeters(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const dlat = (lat2 - lat1) * 111320;
  const dlon = (lon2 - lon1) * 111320 * Math.cos((lat1 * Math.PI) / 180);
  return Math.sqrt(dlat * dlat + dlon * dlon);
}

/** Find the path to the data file, checking dev and dist locations. */
function findDataPath(): string | null {
  const dir = dirname(fileURLToPath(import.meta.url));
  // Dev (vitest/tsx): src/geo/local-geocoder.ts → data at src/data/
  const devPath = join(dir, "../data/mvd-geocoder-data.json");
  if (existsSync(devPath)) return devPath;
  // Bundle (dist/index.js): data at dist/data/
  const distPath = join(dir, "data/mvd-geocoder-data.json");
  if (existsSync(distPath)) return distPath;
  return null;
}

const PLACE_SCORE_THRESHOLD = 0.6;
const MAX_INTERSECTION_DISTANCE_M = 30;

export class LocalGeocoder {
  private data: GeocoderData | null;

  constructor(data: GeocoderData | null) {
    this.data = data;
  }

  /**
   * Search for a place/POI by name. Returns the best match above threshold, or null.
   * Uses token fuzzy matching to handle typos and encoding variations.
   */
  searchPlace(name: string): GeoPlace | null {
    if (!this.data || !name.trim()) return null;

    const normalizedQuery = normalizeText(name);
    const queryTokens = normalizedQuery.split(" ").filter(Boolean);
    if (queryTokens.length === 0) return null;

    let bestScore = -1;
    let bestPoi: OsmPoi | null = null;

    for (const poi of this.data.pois) {
      const normalizedName = normalizeText(poi.n);

      // Count how many query tokens match the POI name
      let matchedTokens = 0;
      for (const token of queryTokens) {
        if (normalizedName.includes(token)) {
          matchedTokens++;
        } else if (token.length > 3) {
          const words = normalizedName.split(" ").filter(Boolean);
          // Check if any word is within edit distance 1
          if (words.some((w) => levenshteinDistance(token, w) <= 1)) {
            matchedTokens++;
          }
        }
      }

      const score = matchedTokens / queryTokens.length;
      if (score >= PLACE_SCORE_THRESHOLD && score > bestScore) {
        bestScore = score;
        bestPoi = poi;
      }
    }

    if (!bestPoi) return null;
    return {
      lat: bestPoi.la,
      lon: bestPoi.lo,
      displayName: bestPoi.n,
    };
  }

  /**
   * Find a street intersection by searching for the closest node pair between two streets.
   * Returns the midpoint of the closest nodes if within MAX_INTERSECTION_DISTANCE_M meters.
   */
  searchIntersection(street1: string, street2: string): GeoPoint | null {
    if (!this.data || !street1.trim() || !street2.trim()) return null;

    const norm1 = normalizeText(street1);
    const norm2 = normalizeText(street2);

    // Find all matching streets for each name
    const matches1 = this.data.streets.filter((s) => allTokensFuzzyMatch(norm1, s.n));
    const matches2 = this.data.streets.filter((s) => allTokensFuzzyMatch(norm2, s.n));

    if (matches1.length === 0 || matches2.length === 0) return null;

    let minDist = Infinity;
    let closestNode1: [number, number] | null = null;
    let closestNode2: [number, number] | null = null;

    for (const s1 of matches1) {
      for (const s2 of matches2) {
        for (const n1 of s1.nodes) {
          for (const n2 of s2.nodes) {
            const dist = approxDistanceMeters(n1[0], n1[1], n2[0], n2[1]);
            if (dist < minDist) {
              minDist = dist;
              closestNode1 = n1;
              closestNode2 = n2;
            }
          }
        }
      }
    }

    if (minDist > MAX_INTERSECTION_DISTANCE_M || !closestNode1 || !closestNode2) return null;

    return {
      lat: (closestNode1[0] + closestNode2[0]) / 2,
      lon: (closestNode1[1] + closestNode2[1]) / 2,
    };
  }
}

/**
 * Like allTokensMatch but allows 1-edit-distance tolerance for tokens ≥ 4 chars.
 * Local copy to avoid circular dependency with geocode.ts.
 */
function allTokensFuzzyMatch(query: string, target: string): boolean {
  const queryTokens = query.split(" ").filter(Boolean);
  if (queryTokens.length === 0) return false;
  const targetWords = target.split(" ").filter(Boolean);
  if (targetWords.length === 0) return false;
  return queryTokens.every((token) => {
    if (target.includes(token)) return true;
    if (token.length <= 3) return false;
    return targetWords.some((word) => levenshteinDistance(token, word) <= 1);
  });
}

/** Compute Levenshtein edit distance (local copy to avoid circular dep with geocode.ts). */
function levenshteinDistance(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  const prev = Array.from({ length: n + 1 }, (_, j) => j);
  const curr = new Array<number>(n + 1);
  for (let i = 1; i <= m; i++) {
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      curr[j] =
        a[i - 1] === b[j - 1]
          ? prev[j - 1]
          : 1 + Math.min(prev[j], curr[j - 1], prev[j - 1]);
    }
    prev.splice(0, n + 1, ...curr);
  }
  return prev[n];
}

let _instance: LocalGeocoder | null = null;

/** Returns the singleton LocalGeocoder, loading data lazily on first call. */
export function getLocalGeocoder(): LocalGeocoder {
  if (_instance) return _instance;

  const dataPath = findDataPath();
  if (!dataPath) {
    console.warn(
      "[LocalGeocoder] Data file not found. Run: npm run build-geo-data\n" +
        "  Falling back to Nominatim for all geocoding."
    );
    _instance = new LocalGeocoder(null);
    return _instance;
  }

  try {
    const raw = readFileSync(dataPath, "utf8");
    const data = JSON.parse(raw) as GeocoderData;
    console.error(
      `[LocalGeocoder] Loaded ${data.pois.length} POIs, ${data.streets.length} streets (${dataPath})`
    );
    _instance = new LocalGeocoder(data);
  } catch (err) {
    console.warn(`[LocalGeocoder] Failed to load data: ${err}. Falling back to Nominatim.`);
    _instance = new LocalGeocoder(null);
  }

  return _instance;
}

/** Reset the singleton (for testing). */
export function _resetLocalGeocoderSingleton(): void {
  _instance = null;
}
